In [67]:
import numpy as np

nums=[1,2,3,4]
print(nums)
print(type(nums))

[1, 2, 3, 4]
<class 'list'>


In [68]:
nums=np.array([1,2,3,4])
print(nums)
print(type(nums))

[1 2 3 4]
<class 'numpy.ndarray'>


In [69]:
marks=[[1,2,3],[3,4,5]]
# print(marks)
marks=np.array(marks)

print(marks)


print("Dimension: ",marks.ndim)
print("Shape: ",marks.shape)
print("Size: ",marks.size)
print("Data type: ",marks.dtype)

[[1 2 3]
 [3 4 5]]
Dimension:  2
Shape:  (2, 3)
Size:  6
Data type:  int64


In [70]:
#create zeroe array

myarr=np.zeros((2,2))
print(myarr)

[[0. 0.]
 [0. 0.]]


In [71]:
myarr=np.ones((5,2))
print(myarr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [72]:
myarr=np.ones((2,5))
print(myarr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
print(myarr.dtype)

# myarr=np.ones((2,5),dtype=int)
myarr=myarr.astype(int)
print(myarr)
print(myarr.dtype)


float64
[[1 1 1 1 1]
 [1 1 1 1 1]]
int64


In [74]:
marks=[[1,2,3],[4,5,6]]
marks=np.array(marks)
print(marks)
print('-------')
print(marks[0])
print('-------')
print(marks[1])
print('-------')

print(marks[0][1])
print('-------')

print(marks[1][2])


[[1 2 3]
 [4 5 6]]
-------
[1 2 3]
-------
[4 5 6]
-------
2
-------
6


In [75]:
nums=np.array([1,2,3,4,5,6,7,8,9,10])

nums=nums*10
print(nums)


filterednums=nums[0:5]
print(filterednums)

print(nums[5:])

print(nums[::-1])

[ 10  20  30  40  50  60  70  80  90 100]
[10 20 30 40 50]
[ 60  70  80  90 100]
[100  90  80  70  60  50  40  30  20  10]


In [76]:
data=np.arange(5)
print(data)

data=np.arange(5,10)
print(data)

data=np.arange(1,10,2)
print(data)

data=np.linspace(0,10,5)
print(data)

[0 1 2 3 4]
[5 6 7 8 9]
[1 3 5 7 9]
[ 0.   2.5  5.   7.5 10. ]


In [77]:
#generate random numbers

data=np.random.rand(5)
print(np.floor(data*100))

[30. 57. 34. 92. 80.]


In [78]:
randomNums=np.random.randint(1,10,5)
print(randomNums)

[5 3 1 1 1]


In [80]:
arr=np.arange(1,11)
print(arr)

final=arr.reshape((5,2))
print(final)



[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [82]:
print("Mean: ",final.mean())
print("Sum: ",final.sum())
print("Max: ",final.max())
print("Min: ",final.min())
print("Std: ",final.std())




Mean:  5.5
Sum:  55
Max:  10
Min:  1
Std:  2.8722813232690143


In [86]:
print(final)

finalFinal=(final+final)*2/5
print(finalFinal)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[0.8 1.6]
 [2.4 3.2]
 [4.  4.8]
 [5.6 6.4]
 [7.2 8. ]]


In [88]:
newarr=np.array([[1,2,3],[4,5,6]])
print(newarr)

print(np.sqrt(newarr))  

[[1 2 3]
 [4 5 6]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [89]:
print(np.sqrt.__doc__)

sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the non-negative square-root of an array, element-wise.

Parameters
----------
x : array_like
    The values whose square-roots are required.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``, locations within it where the condition is False will
    remain uni

In [93]:
mydata=np.array([1,2,3,0,5,4,0,34,2,0,24])
print(mydata)

#get non zero values
print(mydata[np.nonzero(mydata)]) 



[ 1  2  3  0  5  4  0 34  2  0 24]
[ 1  2  3  5  4 34  2 24]


In [94]:
mybin=[1,1,1,1,1,4]
print(np.bincount(mybin))

# [0,5,0,0,1]

[0 5 0 0 1]
